version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

jobs:
  keep-alive:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: 安装依赖
          command: |
            python -m pip install --upgrade pip
            pip install playwright
            pip install asyncio
            pip install requests
            pip install python-dotenv
            playwright install chromium
      - run:
          name: 运行脚本
          command: |
            export TG_BOT_TOKEN="${TG_BOT_TOKEN}"
            export TG_CHAT_ID="${TG_CHAT_ID}"
            python idx.py
      - run:
          name: 提交并推送 cookie.json（如有变更）
          command: |
            git config --global user.name 'circleci[bot]'
            git config --global user.email 'circleci[bot]@users.noreply.github.com'
            git add cookie.json || true
            git diff --quiet && git diff --staged --quiet || git commit -m "Update cookie.json"
            git push || true

workflows:
  version: 2
  keep-alive-schedule:
    triggers:
      - schedule:
          cron: "0,30 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - keep-alive
